language: scala
jdk: oraclejdk8
scala:
   - 2.11.8
services:
  - postgresql
env:
  - JDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/travis_ci_test JDBC_DATABASE_USERNAME=postgres
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
