DELETE FROM Report;
DELETE FROM Company;

INSERT INTO Company(Name, CompaniesHouseIdentifier) VALUES ('EIGENCODE LTD', '10203299');
INSERT INTO Company(Name, CompaniesHouseIdentifier) VALUES ('BRIGNULL LIMITED', '08456262');

INSERT INTO Report(Identifier, CompaniesHouseIdentifier, FilingDate, AverageTimeToPay, PercentInvoicesPaidBeyondAgreedTerms, PercentInvoicesPaidWithin30Days, PercentInvoicesPaidWithin60Days, PercentInvoicesPaidBeyond60Days, StartDate, EndDate, PaymentTerms, MaximumContractPeriod, PaymentTermsChanged, PaymentTermsChangedComment, PaymentTermsChangedNotified, PaymentTermsChangedNotifiedComment, PaymentTermsComment, DisputeResolution, OfferEInvoicing, OfferSupplyChainFinance, RetentionChargesInPolicy, RetentionChargesInPast, HasPaymentCodes, PaymentCodes) VALUES (1, '10203299', '2015-12-27', 78, 21, 9, 70, 21, '2015-05-28', '2015-11-27', 'We don’t have a single standard payment period.', 'Our maximum payment period is 90 days', FALSE, '', FALSE, '', 'All the information you need is on our website', 'All of our contracts contain an industry-standard dispute resolution process. This can be found at http://www.eigencode.io/suppliers/disputeresolution', FALSE, TRUE,FALSE,FALSE,FALSE, '');
INSERT INTO Report(Identifier, CompaniesHouseIdentifier, FilingDate, AverageTimeToPay, PercentInvoicesPaidBeyondAgreedTerms, PercentInvoicesPaidWithin30Days, PercentInvoicesPaidWithin60Days, PercentInvoicesPaidBeyond60Days, StartDate, EndDate, PaymentTerms, MaximumContractPeriod, PaymentTermsChanged, PaymentTermsChangedComment, PaymentTermsChangedNotified, PaymentTermsChangedNotifiedComment, PaymentTermsComment, DisputeResolution, OfferEInvoicing, OfferSupplyChainFinance, RetentionChargesInPolicy, RetentionChargesInPast, HasPaymentCodes, PaymentCodes) VALUES (2, '10203299', '2016-06-27', 84, 19, 9, 60, 31, '2015-11-28', '2016-05-27', 'We don’t have a single standard payment period.', 'Our maximum payment period is 90 days', TRUE, 'All the information you need is on our website', FALSE, '', '', 'All of our contracts contain an industry-standard dispute resolution process. This can be found at http://www.eigencode.io/suppliers/disputeresolution', FALSE, FALSE,FALSE,TRUE,FALSE, '');
INSERT INTO Report(Identifier, CompaniesHouseIdentifier, FilingDate, AverageTimeToPay, PercentInvoicesPaidBeyondAgreedTerms, PercentInvoicesPaidWithin30Days, PercentInvoicesPaidWithin60Days, PercentInvoicesPaidBeyond60Days, StartDate, EndDate, PaymentTerms, MaximumContractPeriod, PaymentTermsChanged, PaymentTermsChangedComment, PaymentTermsChangedNotified, PaymentTermsChangedNotifiedComment, PaymentTermsComment, DisputeResolution, OfferEInvoicing, OfferSupplyChainFinance, RetentionChargesInPolicy, RetentionChargesInPast, HasPaymentCodes, PaymentCodes) VALUES (3, '08456262', '2016-03-21', 38, 16, 84, 9, 7, '2015-09-21', '2016-03-20', 'Our standard payment period is 30 days from receipt of invoice, subject to our weekly payment run.', 'Our maximum payment period is 60 days. However, this relates only to contracts with a value above £100,000 per month.', FALSE, '', FALSE, '', 'All suppliers must submit invoices and all other documentation through our online system. Our supplier FAQ can be found at www.brignullltd.com/suppliers/suppliersetup.asp', 'We have a dispute resolution process. You can find details at www.brignullltd.com/suppliers/contract-disputes.asp\n\nWe support Alternative Dispute Resolution (ADR) processes such as arbitration', TRUE, TRUE,TRUE,FALSE,TRUE,  'We have been signatories to the Prompt Payment Code since 2014.');
INSERT INTO Report(Identifier, CompaniesHouseIdentifier, FilingDate, AverageTimeToPay, PercentInvoicesPaidBeyondAgreedTerms, PercentInvoicesPaidWithin30Days, PercentInvoicesPaidWithin60Days, PercentInvoicesPaidBeyond60Days, StartDate, EndDate, PaymentTerms, MaximumContractPeriod, PaymentTermsChanged, PaymentTermsChangedComment, PaymentTermsChangedNotified, PaymentTermsChangedNotifiedComment, PaymentTermsComment, DisputeResolution, OfferEInvoicing, OfferSupplyChainFinance, RetentionChargesInPolicy, RetentionChargesInPast, HasPaymentCodes, PaymentCodes) VALUES (4, '08456262', '2016-09-21', 36, 11, 89, 4, 7, '2016-03-21', '2016-09-20', 'Our standard payment period is 30 days from receipt of invoice, subject to our weekly payment run.', 'Our maximum payment period is 60 days. However, this relates only to contracts with a value above £100,000 per month.', FALSE, '', FALSE, '', 'All suppliers must submit invoices and all other documentation through our online system. Our supplier FAQ can be found at www.brignullltd.com/suppliers/suppliersetup.asp', 'We have a dispute resolution process. You can find details at www.brignullltd.com/suppliers/contract-disputes.asp\n\nWe support Alternative Dispute Resolution (ADR) processes such as arbitration', TRUE, TRUE,FALSE,FALSE,TRUE, 'We have been signatories to the Prompt Payment Code since 2014.');
